env:
  global:
  - # GITHUB_SECRET_TOKEN
  - secure: "PqrFmin9aLra1MGCFBbc8DxpOd20dH5fE90kYUGNVB3eYpe9I1GgBnP1Ywq+y/x+wuzfSvWDrZVnizsWgtw4R3X8pNtLKs7HjODrwcc408+pYPkvLnogC/POpBaLWn4QjIO6+veGqnxIWCd9iqSF+uiKdrG4dZLUPER6v2sYY0k6/W2LO3GUx3hsglBC5J7xWexHh2Qp6hmNg6CQC32LLD1mzxNgkEFf4GQJewedW+My8jgwYcsqYvxC+pbXYgA0WnfCOeSSzKG+WsYH3GPRF5yn1mURLLY11OxqApGOEW26p0x8SZ6z7VehS6luW8zn3mQqadkLigKndNMN+WtXlFMdHXsO5lYDPC2VVlZCHr6bDyxOkDUARnLGOSQmy1Pvxv/1/UiZqPwSYlWILMKj3vYEHMAlnEhokNMONXaxphFU7vuIiywWFXBqoYJ089JjmLTqZ06BiKd6XisOwesiOkWqIMYMbZyHia84PPVKJ6XC8V9bah/Qo/EIpH95bh/g9Hr+t9wxAHsJlV2sefvZGu/PdDcOwIXl91wIht6dvCKtsyNpZkTRqSKhBj8ZKX8ujAL0/KEzF4yfbSba8SzTO7gjx3QrF2IxnHlXSIfZlgsWPpYzqfYabS+PcAl4pSKBsJIAmnk72E4BYK0+KoaOiHEldObUcvghLN24RH7DUdw="
  - # SONATYPE_USERNAME
  - secure: "KgQxhs4NprMHAzAvZ4i3oMx0J+KtSJ54aUc+k6jnKNe4w6iYSq83/6KvuqIK3w3NIAG1FBpuhWVq6l2z1DrmVRWVCASm6snNoHklQ+/oLRsi2XhhiXEW/w5ia9L10mlsdIUmiVm8z1QxW5biIc0IEuIVu/0C3Sr1h8MXLSRqovBTWQEVYpZt9ic2Od0gPsElW8k2rAFJrCfpxwHMkOJPKbQQ8XhZU29b79gz8hZjWraOI8oZzDx8X1x4k3vkZ0xFluY/qNeJGe9en7yTV1SUoseetuoWNB7+uAZzlbrbSPRW1KQJO106OFqKYDJ9gDnLlpiKPS5yYO+0cZKnwQWPhGo8Pi3C+a99UuuvTsaGW7+cRTrFB1qiKQmj3DEyWbe0RUZXYsrvffrv109mNJingvR2sHNkXcS4xtkSRzKmd1xKApHNYSiilMBpjuR0bzfK6G6hyK3jVOgfk0jZCSUx1t3oq5v1QGJT3xudux/Dlw4tMegmV1HnHPnPKwYcsaARdNdoCErbWYn4Ou4bkhDe1rNyh6guAQMWyCHFv4laaPK5CIMUTtFGo1FY7jzY2fH/i6fE2C8iMrgBSFEvWABTXbeS8v6Ic390wp6MsBKwSNAb4ydWq3NoXk4dYGlAjVWMeJdz7HeI/TDqHg8h53iTbAj7T/tPGkq1BIbmvnqVmRk="
  - # SONATYPE_PASSWORD
  - secure: "0iglkxxoHBtgqyY2TTf8+hfIYL1kBKYNwQfhV0NepJ3/ZpMDYCGSqZsYb7vynyjL/A2Iq8OuZHA5ITsfT4P+HA8gUIDy1sLYJ43jbXuTkl6rETnFHaKiN/iSDCNfiNtuO9OuorUgNVeotxUwur3WDCYkdLKYD07N3EU8xjpIzAjqqUYmTMGVnKnGOCIMBV9bGB1pgrPqQNRAAt1kcbFCdZSwkAYCjcssIvuGk8hKJa6mYDHFRhLcfeTy/YxEpQQmDp9pyOuYjbd5Bi1auE7zleN2KTTdxelUGzca2EgFQWTPf3rXfNE/K3yJ0vEHJF2ExJ00+zNsNCQDuJwHx3S6EOKO3+NfzKI6yVtlAfToFhFvUvyIXrcJhpvwgingheOS8cmYUAzj51vebyD/KT3OM0RmAyGc3TJjPISAQJzNX/WDSRMCc+A135b+hES9ad8kBtu9YoNZEPoZW7LtlKii4lcycMQTJwp6X2qS1P5JwVg6x+1x5UIOkV0QSM4DmpA0JGvx0TRoZ4uoeyheRnW/SPhGaiscPNBQoQvLIJW+C/V2yy0/UVmyDn9wvPR3JldXvRr15yF7k/jb8i/AaCHq0jRU4W6a4ZzviP253dr/tDiD0pXoW5ZTkQs8m4wF7TN3cdDXc/uQ2ONT14Msup+Wm9SmfG5G8WweqHKb5VqqWvc="
  - # GPG_KEY_ID
  - secure: "V7HmOTBBupVSwKS57o2TWC4RElKZxXz9U0fbkZ9ZBhK609QXj/jHxwRkb4uqHxmpsY49WJqlCOkmkakseLLu2eQE/PRiylfclMJKDOtS4zdNc68xsW2lQ9g6uUhvO4R0sOg37zZoVrGYoYCb2f31rlmyVKmdNBFxpOpfIUAwH4ip++vsXUkUXD0GB5DERIw4jRCew4BlgMARACW1EFDgLnXYHJ5KVeN953vEkpkuNgoL0TjTRSN63M5YIMAYpIFMbaJyqQmvN7sLzT3RVaBvkqbNwNGtIC6yJModnFzZzCZ7Is4lTXfEJMo9dWfSg8zhYTlhKz8NjAUVOHrX9QI0agg6ZtKbbJtXhhc9bTvRIH+s9scEA+mC3q2hiCivVN6GG5gpkCNH03Wf23aiM/Lq8y6qBaa/Lnx0xYH7A1yamrX3I4E92HrQfEDXB36d+eh2rb7OgBO2yJ0euCGBDz/Ib+rpytVgOIJnu38P3uXKGe+aWGPlGp++RwaDZAK1dk257BbHBhQ67Pwo7ze2wSZAmdiuNY4VSm9LWU8aMcu+3hksTmw2BPhPptHBph27B4+WbiIgAWiHFvclipe/Zzj/YPiqCEsRG2mTDttTWq9ULhlEMYvkHlXnU4L1shFU33HeGFXQ4RkaCQ3NU6ue2hPzdas/mAbv3hm2+jDxgYVwZjk="
  - # GPG_PASSPHRASE
  - secure: "WVCD0Ri+rqxBiE6iP/qH5fnE3ZQgT6bsFI4wXkiaAtUokkjrERybQUDV8wEcjY9B8Ch7Z7JP3XFOZPuaWDGC8RnDE2EwCdKDNdgYeE7T2nGTBwVdpU1AxYriYRKTtJ+w6m/pdUebD9c10WsbAghxbPj57fLp7SaH4M/w/5+Trd7KSctg2J0rtOeZT5A6KIivO/nh9RH0Px0lmia21u8nqb0l5Mp906JL3PaMDRGzFu6kBTaiM8fewgdyP8azDYa6JUHMQdHdfJ9sOKcMIDD/cEVd34YbmvwmtFMqliEqXuYKSmy8Sk+BWp41LySvypB7LeO1PFs296/vfIuf280K+pq3u8uoajxiyuXNT4ebVwSGVfeg/aQQG/T7wXW/eJHlR8lZL9zf1ww21Xb9fXIwm+VhKp+0BT9bPnjkJ0E9OlDVa1Ho/g1F+VrL1L+/Z+0pXIOdkiJCIYwUumLbC/Zfftu2DrXQlGIc6G5Z5MSpIkdHeZehxzej2VHyp0YQRxtWdoB0fehQU8MITI9kBqDJteJYxm6wIWLTGdGGomHy9qDA6y2E2D0UX2qJFI7Pnly65Xndga3GjqKaIL1BvyHLhVeFObgi/gho18GknhthvIoQW18S771wCmdGuck7tLsdC9kITivIVHuobnbZFCn3O4zxx/GyUp1xWQhdanNnQaM="
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"

branches:
  only:
  - master
  - dev

language: java

install: true

jdk:
  - oraclejdk8

notifications:
  email:
    - rahuldashing@gmail.com

before_install:
  - pip install --user codecov
  - chmod -R ug+x .travis
  - ls -lrt $HOME
  - sh .travis/install.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon  logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

script:
  - ./gradlew build jacocoTestReport --scan -s
  - chmod -R ug+x .travis
  - sh .travis/build.sh
  - sh .travis/merge_dev_to_master_gate.sh
  - sh .travis/deploy_gate.sh
  - sh .travis/tag_master_gate.sh

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: YuFwq6wVUnvjiXD67grWdL2zEC8LkgMLTWGCclluwBMEEY4ubJDBiAdrhi4xHDZ9QSIXPpI3gqX+Y4OuMC3SKeHH5Vv8e4MBv2ggxfR3Xlz+5ZWnDHc/uBhtuSip+88jqegE2TIk1YR0Tz0j4QuwPCYQU9CLQNZ28GUhO17RSsKWhCOc98W2KimoF1q9ubRiwB+e36iEXCcilINyr2j9dmTZPRnlAugPBVDbu3xrK06eYB/Li1MZeOvhKDkCbRNQitovX0NMnuiBv+7CC2Z5fxxhOBTsDk2T8VnYz1rZcSstD8Yiq2zaCY4LHt89odqCPGv5lVQxGK2RpAusc2wmGwXJ+F8JJvZQfEls2xoVwMX5tTlP66LVaqK0NvuJr7UUKsO6y2il1SLPcXvAGKxBbSnv0N9qyba1TVA1WSbPx+wNEy6LDftkvxpPEiB0J8c37dEfzH/XQoFKjrjDNFfP0qBvbsvAvTazqjyISNz4ZEpnNt3W4BK7yp/1qZG6QtZMXIwYs6svxIYoTQt26DohR5EPRSllrwqada+8IZf5MeE4VysE/Uadm129nZDql4Ru/KQvhc6d7lHYrqPa98cF4y4wcQg5pqYConwWRWiMmdtiHjG4g7U/ws2OJ5XnmmJqqezCB5caGZ4wnT0DDSNlTXzTzj5HdZesADIxXiw83jQ=
  file:
    - build/libs/time-me-0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: rahulbaphana/time-me
    tags: true