env:
  global:
  - # GITHUB_SECRET_TOKEN
  - secure: "SIEDyx0hiWzdZV1XDN9WSOF4QesLhbQiH4LMchps7sebW5OmgS9YnshmQkbW/54XPQw8dTx3KL9CGquE59syzkyCS1xLPWnOWdQEfV9qkUktY83EKLlxN+EWv070Vtqt3G2mhuHk7X8bTyrk5gxvj+IvwDhh0osBelSxF56wvQPrFsW81E6WaBVjmn/yziwZQVj9w0oJzCbgBuqFkh9BKovSs3EbIpV24opLff4hWLGNf9vViVEbNnX8P8YwWmhZsGsHzz1TiQVH0+DhPqdmFDe/5Q4NJiU9qOTBiHblmR68lm8Ax85uWcMo/gkd1U2TaQdGGP9NkyM373aWL1QyI/heCRMnqQPmJm5YtNW3d0JXC/HUzd/C0jbRMWN+Sm0Ch99+IvjJyYsOBB2ygdkE9SYn9Ur1I+8P324ViQsQr9dcUo29J5RrL49lPxZXr7ZaG5L9nrwyreYCn9KB0SocE9WEL5JPT0GrtsvW4hmnduvVOa/eT49U7CEhcj+2itiF+hQArABol1XXp6qB5wF6ZcDMHLUzY3jzbKrp7Q6tvCbr0ApWmzTyJocFtyF4FoeH85MWhDgvS0y5RoUzSAIMa/uBh4KARDmn2XEpUNRFRpMKfksaU+5Q91gBHkMzivQcTOTW+Z+WhZ6eo7OBj7Gvu54oK/dzgXJlsqm1F5aiAE4="
  - # SONATYPE_USERNAME
  - secure: "ZzE1ILMlIpOnG1jq3RRjFqSiaM/BKoxToQFKL6ZQbEj8XbMaR5VNirRhetSXQDWqLCLb6I/Yu38tarXCFlBWMFtONdGd7SI5AB2MMt3EWfZ+Rt8nn+QYxVavGBpqTf+AXfHpyJXB0zQ9J3suU8y06WAoxVJ0/p3083juMDu4/dPgg5BeSUbRAwMfO4YDlfeauX1cQnVQ2WLzKZgVGQsRD4PuwAFaXJbeeUtVnc1MiX5y0v7Y2OeUhmnoz5+efhKMC8nRNdInjuihB0IvdpuvJc2TSBZtl1oA6LX2YJRGXcZr4bpq3GfR7gjBPmwBs2hNyhsTjcbqV5IEku7Pg/whQDep/woR8VSn31l3t4tW7rypHOCG8gjKvipcgZm5GHmk041Q+M7WYQECQ9c8TrZrbe4O42IEyu2CUyk/ONYLLFhCL2tRC7nyye5Qnp3+1s1bhrFWK6vGf4B+mLXdG+ZZEnum2uYqvt6D16nGDeNEuRbgUZJhhBCUuYA0P9Jpz7I9w8SC/F5N5DHLvFmLXFHS+wcvRLH+DOxNSuMRyNcwFKs2BBym1DPSOtLG+BwGT4PC7YPXuVvd1PziljL5xndILQBjRku+X1sTMO8FYZR3BSuiftX+HXHMqz2eJJwYbkmw4JlABzmZnn0tE5hBHRAd/M+0+eK64Wl3Z2Wma3AgjGg="
  - # SONATYPE_PASSWORD
  - secure: "1thGaCnpVnGSHgz6L2cXWsqOzodgwsT6A5I+UMHJZzwrauV9tQ0tMHQgT0zPWGJgx47J0sUBTrIBufi81+wXWL8IYz+F8xUL7dwnEvrIbGdlzTlTzR38mLJAkXsEvSA0F3zkir7oWsr8uRL2LroQrNSqQqkXw3cjgfGsDP9IykqIkWPDzgGF9YOyAgvn5IpE292fcbNNGXmn31GYsezurI2IrFgpvup7/3UGCrODQoNhFtTdQdTFtt9jdl9ScUdHlnk29PSNksUT90Omy40x8ImP3uBCMyqAd6jiaFYkplv4gCWyFNFgQX/+ThbIED78FpnoM1pJ1+BDe2rejzV5SdflLOJD3JxVq0vOoRhJD8ajYDAoUYlbC03OTOanNb2f3Em8gJn5kVEDQf3rYRQJmvErv/ZdPBbb3AJ9qtSiwG2MsbxN8M9ZQ1WI7JDyteF5c88Cx37lHRkrAtg0YrTxnN5gEEiZOznpZdbnt7B1+El2LH/AYEOMWoFc+kEbg0xVN8q+zuj0gS1ldGmMgILKwikVrXHknsklKtGxcRPX1isQObLivMR2uPuQJiPaRGCkKa52y5c57MnPN02dnxKUIPOcJUBnMibaCAW3uU20srnACyMtGIkV/lhN5FOQu2+JZpohlO2kZ+jvIood41IXSm0AxbGtr233xoumvUvu2YE="
  - # GPG_KEY_ID
  - secure: "d59s7qRVbbvP6RGseR7Ecc+PUJKKyj/PcBf7b3P3JOrcm2tQ7V976oC3nZX4E+aqeR4X6kM5E8f/98XOtBvVA/cvZ/LNwljM72QITAG9iJNtbHLGHfo+LHZEkildcmnPxakD5C4LXoFBogFUCB1RsJ9vwFHHfgx3uay212qgjzX7Hbe5Azg1i2Wornl8Rl5+aa5KbmVpbr86uQoQ3NLwaXNlMx92J54ZbKlkTDH0cWEoLvic8kEQZDVnWl4j1StNdPbPm1m5f+66vqNNJvcdV4SaIgisTNv9SbW2SCB37nbo9a9T45B0dA8leNeRPqIhNhpAqXk6BYqmOKmkphs14cSsAvKahPke+hgLr4rvQM/R3H+pMQKhfz/N7HweA/5m81a9N5jZWpcAA0lAaWYOebt12wVrr3r6v2PPExBs9FoikR4Y86vCC9BYcSRLU/i6oFWP2tnHmTesEOOTvwAzMjcH2ude1GIBU0ZIqFeeIi7AwGETOz2/zjOhBPfFZGw5Osjze4s1DOZuQx+LxLk1RhH+QKm+/rUmwT1WB4V2gqLhKy5apVGjOioyljwwbaWhEnIeRJRl/OLm92SH8zGnXN/MHd3Az0E4xKhArac3RxhjeoYpVtPcb8wI3SAR7qJJt5ggklUUPK5+asOMte0Y6+tFuGaoWmMQ5uh576RVGW4="
  - # GPG_PASSPHRASE
  - secure: "EVo9Py38uX9ve5AcF1XoPQB36cCMJ5rmLA4iMhMwSvv8coPnqhgP4B7jrCHP4lHiQk7fG9Wm9kj64chG6a0V7+Qb8VF2usWR3/22m2EJNvSNAQM3e8DeH3ENfe2T4IQSofd9eGr56ofyQ1bQCNQNvwrU5MVIHC44e1vcDsMCitVOiSVoqps4CDhhAYB2QCiRFtp4OTD3XfLaNtLS0ZtaV0aIieg6aH0ctlggQcLsvr0qpZzyl/hmBlYZNup2mI/Z37njITS3/7MSZNvjLM9G3cMekrhE/Sp+ruQoHggoCXr+GF78pf9n6qkuga5wgBVIquZIq2P9g5NqfX1qb3IShkWKydVgZG447aB4SU2kCpYA5LHhtyoX3ZOxHYzD1x6kEDqbANqs3mvmGJosKeoKsIcUHypwZiU2iSArHdVBWzy5UoE5A/XNtekgvoJCBoVAhzr1ibC+1RLXE+AuFb8FvAE7OVKbezwVE+W9ymnry9qTD2qTMobGddNa9og0JEz+V+PzGhPCJ47202u598cboX5Z8tlU9cnvriwVWyZMAgDlQxEEE6OHiJimS8kR4DP7BeKu5k42D4x2c7EBeKYlEJW0yjSr6vL7u7wE1Xx/OGUaGf8QZ4iny4RA+mBHZdvUxK+Z9sRhMTjpFwzy2MFF+wrfqyEWpDG4VdODLNrvT8s="
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"

branches:
  only:
  - master
  - dev

language: java

install: true

jdk:
  - openjdk8

notifications:
  email:
    - rahuldashing@gmail.com

before_install:
  - pip install --user codecov
  - chmod -R ug+x .travis
  - ls -lrt .travis
  - sh .travis/install.sh
  - sh -lrt .travis

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon  logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

script:
  - ./gradlew build jacocoTestReport --scan -s
  - set -e
  - chmod -R ug+x .travis
  - set -e
  - sh .travis/build.sh
  - sh .travis/merge_dev_to_master_gate.sh
  - sh .travis/deploy_gate.sh
  - sh .travis/tag_master_gate.sh
  - sh .travis/tag_master.sh

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: YuFwq6wVUnvjiXD67grWdL2zEC8LkgMLTWGCclluwBMEEY4ubJDBiAdrhi4xHDZ9QSIXPpI3gqX+Y4OuMC3SKeHH5Vv8e4MBv2ggxfR3Xlz+5ZWnDHc/uBhtuSip+88jqegE2TIk1YR0Tz0j4QuwPCYQU9CLQNZ28GUhO17RSsKWhCOc98W2KimoF1q9ubRiwB+e36iEXCcilINyr2j9dmTZPRnlAugPBVDbu3xrK06eYB/Li1MZeOvhKDkCbRNQitovX0NMnuiBv+7CC2Z5fxxhOBTsDk2T8VnYz1rZcSstD8Yiq2zaCY4LHt89odqCPGv5lVQxGK2RpAusc2wmGwXJ+F8JJvZQfEls2xoVwMX5tTlP66LVaqK0NvuJr7UUKsO6y2il1SLPcXvAGKxBbSnv0N9qyba1TVA1WSbPx+wNEy6LDftkvxpPEiB0J8c37dEfzH/XQoFKjrjDNFfP0qBvbsvAvTazqjyISNz4ZEpnNt3W4BK7yp/1qZG6QtZMXIwYs6svxIYoTQt26DohR5EPRSllrwqada+8IZf5MeE4VysE/Uadm129nZDql4Ru/KQvhc6d7lHYrqPa98cF4y4wcQg5pqYConwWRWiMmdtiHjG4g7U/ws2OJ5XnmmJqqezCB5caGZ4wnT0DDSNlTXzTzj5HdZesADIxXiw83jQ=
  file:
    - build/libs/time-me-0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: rahulbaphana/time-me
    tags: true