env:
  global:
  - # GITHUB_SECRET_TOKEN
  - secure: "ln1YhRgWcInjJ4JdUvFTE8ci5ohK0VazKHkT44N2xiBR0qKouLcf+VUGRtIqIGiulqtkU2h0V4Pi6tMu4Bgs1rrza9rCTifVfoGEgcqJ0Y9sk2lQ7uaRXJBnp3ndn7Qk87bod+Dp2nI7CHCp5MJk/W6osexum+AmmjbUJvmfK9UJVrXp+b/AbuNZfPzNYY6beTsfrWp8tzBq3M2+DL8CF5/wzGWNmwvZiAZrIGNGe65GoKNdCbAB0X3em/DALRWtdPHHXm2rwqEyuU/j1TslbQsXxC7oB5bV566mF3kYL5q28JG1qvI+2kbp84piSG9tk/XniQN4pS4hHcJNu/9nEyxKNg36/I68fd6eD/w0cYVsUQvgNOylpOzbXKqkAyGArvnRC3RZm3FCOG9eSoFq8+NgnaI/i3qPLSXmtpA76aUoy4yCG2r2sUtOLgGulKKuiPfZqBCD6WZZpLnyPkHRkgKgNTCnLVy29r6wKomdd9SNbevP26e4HSi/VC1HRCBZ3NON1tug/33a0Th0aY6jzNbjcNA9TKhhijF/IUkS3quJIgeloCh0yGcthX64MKm4F21pNgDNtjx1cAjiKOZ9NNuLqzLtDcXBCSKgmBPL8l37nmZKY5YkgXDexG67pqoH92PrfJ76v6nBaFbuT1vw+4vX6QY/8U6fEWtlwhSj1eg="
  - # SONATYPE_USERNAME
  - secure: "JM/iVNkijOd9JiM2jj0qEvBQw1BtD6vhrEjD+f/mV6+72ZQd94W0lihRk14ey4dtwegdGC68qgLk648gDKy1911JeYHR3TzwcW4MDylehVzUmPXAqCv3TZLnedrDpTK/DJMekA2lBb+oB6L922vlOzfixRW2zVH0p/tFngblNQP3lKojatFebMzQl+e4ZBkJeQsCq+xY+1YYR+23Rc3DqJCrO7KedLMUyevp1hTwIOdD2SkNekNSQAK9UZ1wWryrFRqcUxZXzCZRE+dyb0ZkUe+8RTITjqVPmQTxfKP/Ax+hIinJrnceNUyPf1S5lO0f6UHaoh8lPKVQh+9WiA48+DxxbV89aGopIM+DNO+8vq44sVNzo7kSk6HYfDT6fU71bRKGPNSTmZH4V/2HaIdsgpW2SJabgZR6xMQNZIYJpxBq4EZZUVL+TWVOusvxkftDOnG4inaFEUgdsQIb+mwQSs+9QsDu190gIQZdqFdhn/Ywa/9A+ETGurjluX1IX3YJCsaZUBaQJiTcjkkPRUJplm05Rym0OGKA0iRVPl+sYSYR+2lloT9lDnCOKgCozC2Tftzj0ZQTnOmGEL/vnae6U8UgBDjlMBeghuoeJNnW9LGsq7KjQfeYYFy7g6Y0c5s8kTKR1Bv3MIBL5CT4Ii3vwTl94kY0NzofBELYPV4Yfjk="
  - # SONATYPE_PASSWORD
  - secure: "08gP4pI2ka/VccqRnAFttcPEX6of4ndg+3r8l2NuiRU8zCsJnbc/uXjAwL5gMQoeMQrkQxetL7qcv3EBd+qxXND9h6vpoCv3Q53AZn3DL2ewjEpXCPkG2Zp5WqzncygkLFNMauqBhq47Dekq6df3lTzVoLy+NF5i1f0pQyBKDqQQcS8O2Lz7HwdO/nesQBUg3Arlx02rJ1Ffx6AsfJpB1+Q12ES54UEf5j0V3u9wb+lvj6GV6PwESjBhUisVAAlYnomE/HAqn133CNWSVxQHo/EqK5dBp5OqPDi/8+ig6Dm0x/rOPhYSAEZHOSge4yqX/qqYHCHqeouyPCQ71DS216mnu1Zq5qMMpeUfpqxJEq8f4u/zmFPt7N7Wr8y+70/n5h40EV5K9zICaav5BouwVgwLRTV2CrZNS5en6kBkbOsiO8LE+n4ZX17bhHHK88aYLv/PHNA8QdTH8OmHbtNZiYQi3FpJbubtv8+hEDh/yoTCJq7OajC7EK5Hyy1jM5RMRJinUazzL8oJXtG9RBROXnUuGQeJVo1nib0BsbbhY9LDunbke+MhOP8qA9CtsPuWkPkSfBFztNpYRQUMiZcK8H1vp8bmEeuHXzT2p5oLovgU2paM6OR21TUuy/Z9S3RTlVd0LwvlKE3LYE562tRn6yqpDjVbD6h64V1hQivDy44="
  - # GPG_KEY_ID
  - secure: "0kmndG9BvdlQYhmwdQkqg6YSKoRnAUsOB0cppUi9epyHsATbJY8BJCnR618UrtSPLi82JOb3egx5fDOCAp9XNZ429uz857XUW2pFc3zEQhTDcbTSB5QlPXpgz96TMvqo/PC/VbacH/jeEXW76skxVB9H5X7JKI1BHwHIjzHr0C/V151znloVJ5tdiSBmZoMXEoM5smDfUXn0vbpWmZlhf6gsVhb8r0pVvd2e8xgJhpLQYKcfjjE20rHBruIe1cCzozxsPMNxG+XnT12k8Nsj3RWnYHi9Gi57UeW7j/DYa/+c6XMrJhO2HV0H/i6jKPHDEUm4gM6qK2+0OvP5mpRZvRCmpFvFaEby2kNWvhj0higwUccqJIJjRm8FgW9GI2yTbkbkKjTrHWa9ouYsG9QY2y2EB1DzEB3Gohuf/IekvXr+V1KrA8vcRkrR5wfB8nOJtrL3QyWwe+fdsO5xRhQuGf7/UkUQPJ2RPtdzvw1qPA/TMfy7Un9OSDd1ymiyxBSTDfBKaqro6KHYEJGWYYPXYWIUnBAVrnqDCpNCDjvF6v+bjQbE3cQcU9qVct4w/eOTa+yzlxhaZ3tj4WDkeetKIL7fAREkIOErxtpj7fEFMddH2nMCkgoRJaehOnkAUbBu+rXVKkfSmeItItGB9MDr88J7pF5xVnBBnZoDKirx0as="
  - # GPG_PASSPHRASE
  - secure: "J3/aaAach86ZBNsvG6T/nwPRNIpu3p8oTa5zjq6IIgQY7O8UhSxR9V4rJHPSOUUyRaOinhmMtv/sZxuXJB3FW6tmhwfVFoALlfDUCRtagBqUpS637FXNwLqxdwCmqiNOb2lS8udBhxDVAeWm4E2TvfCjQeJExWTWCt8XT3Fl+igGR49DSL51B2Yrg7JNQXifL843HnBh9Cp3Uxfvesgw6o/rIPoWAViLwQBJ5Hknhkz15E4FAA7zz7sGNZdWzlxmSnqvDwWARAKNPvfOifetzE4ZzSYCY4V9T6GgJs4k//YFaYi9K3DDjlz8Le7T82ajQkslMhZu1pXvhY3/RU5gEOLmP145o5ic+7SsBd7FOSzqHBWJ9W8XwD+Vvujdtwjz73L0jc8LlJZasOjroLqnSkxELlS2I8PigQBQSIhui610hoIAhYTmWSLTAwbqHJxdbmPRcZfGivBESHcBpJeUStAaIZVbKPYQo3/LqWdltTGrqfjijO3OCC31vD5KHw9bg0BxQSJZ6ZprIy3YtM/+x3cZX1N8o1BmU1mhNhG23iK7zeTELCGkSolF3G2B1MsKajGrxmhHXVzV9bnWT+GFJkEuWxKrw8QNTDNMKdCSG2fzuMkMChnK2XxV/o6SQHNmzrv7aOE9jl3a/qzMOmhX94fM0xohLeKID1yht9TSkws="
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"

branches:
  only:
  - master
  - dev

language: java

install: true

jdk:
  - oraclejdk8

notifications:
  email:
    - rahuldashing@gmail.com

before_install:
  - pip install --user codecov
  - chmod -R ug+x .travis
  - echo $GITHUB_SECRET_TOKEN
  - echo $SONATYPE_USERNAME
  - echo $SONATYPE_PASSWORD
  - echo $GPG_KEY_ID
  - echo $GPG_KEY_LOCATION
  - ls -lrt $HOME
  - sh .travis/install.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon  logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

script:
  - ./gradlew build jacocoTestReport --scan -s
  - chmod -R ug+x .travis
  - sh .travis/build.sh
  - sh .travis/merge_dev_to_master_gate.sh
  - sh .travis/deploy_gate.sh
  - sh .travis/tag_master_gate.sh

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: YuFwq6wVUnvjiXD67grWdL2zEC8LkgMLTWGCclluwBMEEY4ubJDBiAdrhi4xHDZ9QSIXPpI3gqX+Y4OuMC3SKeHH5Vv8e4MBv2ggxfR3Xlz+5ZWnDHc/uBhtuSip+88jqegE2TIk1YR0Tz0j4QuwPCYQU9CLQNZ28GUhO17RSsKWhCOc98W2KimoF1q9ubRiwB+e36iEXCcilINyr2j9dmTZPRnlAugPBVDbu3xrK06eYB/Li1MZeOvhKDkCbRNQitovX0NMnuiBv+7CC2Z5fxxhOBTsDk2T8VnYz1rZcSstD8Yiq2zaCY4LHt89odqCPGv5lVQxGK2RpAusc2wmGwXJ+F8JJvZQfEls2xoVwMX5tTlP66LVaqK0NvuJr7UUKsO6y2il1SLPcXvAGKxBbSnv0N9qyba1TVA1WSbPx+wNEy6LDftkvxpPEiB0J8c37dEfzH/XQoFKjrjDNFfP0qBvbsvAvTazqjyISNz4ZEpnNt3W4BK7yp/1qZG6QtZMXIwYs6svxIYoTQt26DohR5EPRSllrwqada+8IZf5MeE4VysE/Uadm129nZDql4Ru/KQvhc6d7lHYrqPa98cF4y4wcQg5pqYConwWRWiMmdtiHjG4g7U/ws2OJ5XnmmJqqezCB5caGZ4wnT0DDSNlTXzTzj5HdZesADIxXiw83jQ=
  file:
    - build/libs/time-me-0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: rahulbaphana/time-me
    tags: true