env:
  global:
  - # GITHUB_SECRET_TOKEN
  - secure: "SIEDyx0hiWzdZV1XDN9WSOF4QesLhbQiH4LMchps7sebW5OmgS9YnshmQkbW/54XPQw8dTx3KL9CGquE59syzkyCS1xLPWnOWdQEfV9qkUktY83EKLlxN+EWv070Vtqt3G2mhuHk7X8bTyrk5gxvj+IvwDhh0osBelSxF56wvQPrFsW81E6WaBVjmn/yziwZQVj9w0oJzCbgBuqFkh9BKovSs3EbIpV24opLff4hWLGNf9vViVEbNnX8P8YwWmhZsGsHzz1TiQVH0+DhPqdmFDe/5Q4NJiU9qOTBiHblmR68lm8Ax85uWcMo/gkd1U2TaQdGGP9NkyM373aWL1QyI/heCRMnqQPmJm5YtNW3d0JXC/HUzd/C0jbRMWN+Sm0Ch99+IvjJyYsOBB2ygdkE9SYn9Ur1I+8P324ViQsQr9dcUo29J5RrL49lPxZXr7ZaG5L9nrwyreYCn9KB0SocE9WEL5JPT0GrtsvW4hmnduvVOa/eT49U7CEhcj+2itiF+hQArABol1XXp6qB5wF6ZcDMHLUzY3jzbKrp7Q6tvCbr0ApWmzTyJocFtyF4FoeH85MWhDgvS0y5RoUzSAIMa/uBh4KARDmn2XEpUNRFRpMKfksaU+5Q91gBHkMzivQcTOTW+Z+WhZ6eo7OBj7Gvu54oK/dzgXJlsqm1F5aiAE4="
  - # SONATYPE_USERNAME
  - secure: "ZzE1ILMlIpOnG1jq3RRjFqSiaM/BKoxToQFKL6ZQbEj8XbMaR5VNirRhetSXQDWqLCLb6I/Yu38tarXCFlBWMFtONdGd7SI5AB2MMt3EWfZ+Rt8nn+QYxVavGBpqTf+AXfHpyJXB0zQ9J3suU8y06WAoxVJ0/p3083juMDu4/dPgg5BeSUbRAwMfO4YDlfeauX1cQnVQ2WLzKZgVGQsRD4PuwAFaXJbeeUtVnc1MiX5y0v7Y2OeUhmnoz5+efhKMC8nRNdInjuihB0IvdpuvJc2TSBZtl1oA6LX2YJRGXcZr4bpq3GfR7gjBPmwBs2hNyhsTjcbqV5IEku7Pg/whQDep/woR8VSn31l3t4tW7rypHOCG8gjKvipcgZm5GHmk041Q+M7WYQECQ9c8TrZrbe4O42IEyu2CUyk/ONYLLFhCL2tRC7nyye5Qnp3+1s1bhrFWK6vGf4B+mLXdG+ZZEnum2uYqvt6D16nGDeNEuRbgUZJhhBCUuYA0P9Jpz7I9w8SC/F5N5DHLvFmLXFHS+wcvRLH+DOxNSuMRyNcwFKs2BBym1DPSOtLG+BwGT4PC7YPXuVvd1PziljL5xndILQBjRku+X1sTMO8FYZR3BSuiftX+HXHMqz2eJJwYbkmw4JlABzmZnn0tE5hBHRAd/M+0+eK64Wl3Z2Wma3AgjGg="
  - # SONATYPE_PASSWORD
  - secure: "KUivzvT6xloh4qQBNjXy1aIc3Rug52S3HOYtQQ/nQTfXwHe56iSJ5hpkfCvUxe6hjx9eOKSqNWBiFXQFm/ohCHpoIJIKIu9tHJWHiu9j7aNjOTlIPIwq2uLojHkcxCPCsFAVDqAB00we7pWpqv1vmkJ9paxmLzztgR8T9ZYI/vc+0VE9ACBU/rVhNwMculGlYmLK2T3ibHa88trgQad/9qpgL6AuxpriYCR4qgMt9kXBxZDRn6vFCLYJ1VQWi+f2II7+Xz1IwZ/aRKxyWTaAyFdOxDUQl7PaPFUvdDVTVIrIx5i8dSYQBDdK1vsgLrML4CV7OzMWu1sdo9sB7lChrsChjPji44MYcyd+4kG/OnuMBtwWfHin/q0z1uapbJiEbukeZthOnfk/dz+qeTkQ2JZUw2yfKFB+mqi3yd9Vc9S5yIvyCZH8JWW96ToQMpp15tanZWhyF4FycAaz/RYzkprX2Jm0CYYzIcT6eLsy2cTgxnKjS9BXpc2GSCV50GjhvX+fhnh9ByaIJMqQPdR1cN98IGLrbJSy0EsmqqStOisRtIDh1elI4RQNxelZJvuwko0SSWJNIWAZXzMecTl0pDFBKHTQ731YLJzAcmkjcXFijuYgfeoshxgyVpodfWyPbT8yIlrE+7mRfXkj74p28Bsgzw4RWgpMmq22ZiV5vfI="
  - # GPG_KEY_ID
  - secure: "YFNdk1eU2oKd0Om9wWheCKw6hW7YEQmlmWeTifTOksUHzwbLBdULbolsTYYUkW40zoNdEV86M7FiBdwRCAu3v3XQDLBC4aXHQOhEF7AITS0kYi7eLHkh7p6RPDWk1XutcAoZ6LqvB/tRX1r4aSl6Zw9b9FBcLGEWVrIenL482poTfnzi1Enp9laBWZDYJoY2oJDdZzRGAJtYRyo+4R0++PMFnIieGgzbdj+5KvjMXvW+dpmF26OJJsikEgqVFQQI4Op+uL9Bz4osDK6lXvnSQ4TuAB2yYAgN5BIFATND+Yln6rW9ieCj5lAc68ZQAfYvq5O9jDv5Qkinp/bw6mdLNOyzRmGD+71RC+VTrgyex8kEYbT5P7/AB+zw55ZZhAWUEohFn2Q260WP2WaBGMdcFkjNiqngvlIAQn7fioHXhkSG7xrA+5DiBZWcM2PgJA/GijKS20u/1WM0CZNcv/GWwBFDEfr0xzmbL1KIPp8Jyc8nzqcXl+iHkQejBekyoj4Zy0dy23vsW07R0TZnyxrpk7bOVSoDvsq7n++9ZvcPx7/becCnIfz28JWK4bEcDJUECQgHQ3gU242J5owuEz0GrgrKOpXa16CqR7ZSi34sj8JTIRaUqP8+cJMQCfajYYCp4AS1oz2PQQQG40tW0De+2j1pAUQmEZe2r0dB6WN0H3E="
  - # GPG_PASSPHRASE
  - secure: "EVo9Py38uX9ve5AcF1XoPQB36cCMJ5rmLA4iMhMwSvv8coPnqhgP4B7jrCHP4lHiQk7fG9Wm9kj64chG6a0V7+Qb8VF2usWR3/22m2EJNvSNAQM3e8DeH3ENfe2T4IQSofd9eGr56ofyQ1bQCNQNvwrU5MVIHC44e1vcDsMCitVOiSVoqps4CDhhAYB2QCiRFtp4OTD3XfLaNtLS0ZtaV0aIieg6aH0ctlggQcLsvr0qpZzyl/hmBlYZNup2mI/Z37njITS3/7MSZNvjLM9G3cMekrhE/Sp+ruQoHggoCXr+GF78pf9n6qkuga5wgBVIquZIq2P9g5NqfX1qb3IShkWKydVgZG447aB4SU2kCpYA5LHhtyoX3ZOxHYzD1x6kEDqbANqs3mvmGJosKeoKsIcUHypwZiU2iSArHdVBWzy5UoE5A/XNtekgvoJCBoVAhzr1ibC+1RLXE+AuFb8FvAE7OVKbezwVE+W9ymnry9qTD2qTMobGddNa9og0JEz+V+PzGhPCJ47202u598cboX5Z8tlU9cnvriwVWyZMAgDlQxEEE6OHiJimS8kR4DP7BeKu5k42D4x2c7EBeKYlEJW0yjSr6vL7u7wE1Xx/OGUaGf8QZ4iny4RA+mBHZdvUxK+Z9sRhMTjpFwzy2MFF+wrfqyEWpDG4VdODLNrvT8s="
  - GPG_KEY_LOCATION=".travis/secret.gpg"
  - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"

branches:
  only:
  - master
  - dev

language: java

install: true

jdk:
  - openjdk8

notifications:
  email:
    - rahuldashing@gmail.com

before_install:
  - pip install --user codecov
  - chmod -R ug+x .travis
  - echo $GITHUB_SECRET_TOKEN
  - echo $SONATYPE_USERNAME
  - echo $SONATYPE_PASSWORD
  - echo $GPG_KEY_ID
  - echo $GPG_KEY_LOCATION
  - ls -lrt $HOME
  - sh .travis/install.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon  logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

script:
  - ./gradlew build jacocoTestReport --scan -s
  - set -e
  - chmod -R ug+x .travis
  - set -e
  - sh .travis/build.sh
  - sh .travis/merge_dev_to_master_gate.sh
  - sh .travis/deploy_gate.sh
  - sh .travis/tag_master_gate.sh
  - sh .travis/tag_master.sh

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: YuFwq6wVUnvjiXD67grWdL2zEC8LkgMLTWGCclluwBMEEY4ubJDBiAdrhi4xHDZ9QSIXPpI3gqX+Y4OuMC3SKeHH5Vv8e4MBv2ggxfR3Xlz+5ZWnDHc/uBhtuSip+88jqegE2TIk1YR0Tz0j4QuwPCYQU9CLQNZ28GUhO17RSsKWhCOc98W2KimoF1q9ubRiwB+e36iEXCcilINyr2j9dmTZPRnlAugPBVDbu3xrK06eYB/Li1MZeOvhKDkCbRNQitovX0NMnuiBv+7CC2Z5fxxhOBTsDk2T8VnYz1rZcSstD8Yiq2zaCY4LHt89odqCPGv5lVQxGK2RpAusc2wmGwXJ+F8JJvZQfEls2xoVwMX5tTlP66LVaqK0NvuJr7UUKsO6y2il1SLPcXvAGKxBbSnv0N9qyba1TVA1WSbPx+wNEy6LDftkvxpPEiB0J8c37dEfzH/XQoFKjrjDNFfP0qBvbsvAvTazqjyISNz4ZEpnNt3W4BK7yp/1qZG6QtZMXIwYs6svxIYoTQt26DohR5EPRSllrwqada+8IZf5MeE4VysE/Uadm129nZDql4Ru/KQvhc6d7lHYrqPa98cF4y4wcQg5pqYConwWRWiMmdtiHjG4g7U/ws2OJ5XnmmJqqezCB5caGZ4wnT0DDSNlTXzTzj5HdZesADIxXiw83jQ=
  file:
    - build/libs/time-me-0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    repo: rahulbaphana/time-me
    tags: true